namespace MusicPipeline.Profiles;

//you can mark this class static because all of its members are static
// Gotcha
public static class DefaultProfiles
{
	// OK I have decided that the default profile shall be fully sandboxed

	public static readonly Profile DefaultProfile = new Profile
	{
		Name = "Default",
		BackupDir = new(@"[$RootDir]/Sandbox/Sandbox_Backup"),
		CompressedDirs = [new(@"[$RootDir]/Sandbox/Sandbox_Mobile")],
		BrokenSongsFile = new(@"[$ConfigDir]/broken_songs.json"),
		DiagLogFile = new(@"[$ConfigDir]/csLogFile.log"),
		CacheFile = new(@"[$ConfigDir]/dashboard_cache.json"),
		TimingFile = new(@"[$ConfigDir]/timing_history.json"),
		CookieFile = new(@"[$ConfigDir]/cookies.txt"),
		HistoryFile = new(@"[$ConfigDir]/downloaded_history.txt"),
		ProfileFile = new(@"[$ConfigDir]/csProfiles.json"),
		YTDLPExe = new(@"[$UpperRootDir]/yt-dlp.exe"),
		FFmpegExe = new(@"[$UpperRootDir]/ffmpeg.exe"),
		FirefoxExe = new(@"C:/Program Files/Mozilla Firefox/firefox.exe"),
		YTDLPConfigFileOriginal = new(@"[$ConfigDir]/yt-dlp.conf.original"),
		YTDLPConfigFile = new("Null"),
		CheckURL = "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
		CustomYTDLPArguments = "--ppa\" \"EmbedThumbnail+ffmpeg_o:-vf crop=ih:ih",
		SongFileSearchPattern = "*.m4a",
		LyricFileSearchPattern = "*.lrc",
		SleepInterval = 4,
		MaxSleepInterval = 12, 
		SleepRequests = 3,
		MaxCompressThreads = 8,
		MaxDownloadThreads = 6,
		MaxLyricThreads = 3,
		ScannerSleepIntervalSec = 60,
		ChronDaemonSleepSec = 1800,
		MaxStreamReturnLines = 15000,
		StartingWebServerPort = 50001,
		NormalIntervalSec = 1800,
		CleanIntervalSec = 604800,
		NormalStep1 = true,
		NormalStep2 = true,
		NormalStep3 = true,
		NormalStep4 = true,
		NormalStep5 = true,
		NormalStep6 = true,
		NormalStep7 = true,
		CleanSweepDownload = true,
		CleanSweepLyrics = true,
		CleanSweepCompress = true,
		CleanSweepLore = true,
		Playlists = [
		"https://music.youtube.com/playlist?list=PLqcuYaDDgyad1-o1HTVnTiZKoluY5enwk"
		],
		LastCleanRunEpoch = 1785532108,
		LastNormalRunEpoch = 1785673837,
		LogEngine = new(@"[$ConfigDir]/csLogFile.log")
	};

	//This is the actual one, not to be used until pushing to production
	public static readonly Profile WorkingDefaultProfile = new Profile
	{
		Name = "Working Default",
		BackupDir = new(@"~/Music/YT_Music_Backup"),
		CompressedDirs = [new(@"~/Music/YT_Music_Mobile")],
		BrokenSongsFile = new(@"[$ConfigDir]/broken_songs.json"),
		DiagLogFile = new(@"[$ConfigDir]/web_console_stream.log"),
		CacheFile = new(@"[$ConfigDir]/dashboard_cache.json"),
		TimingFile = new(@"[$ConfigDir]/timing_history.json"),
		CookieFile = new(@"[$ConfigDir]/cookies.txt"),
		HistoryFile = new(@"[$ConfigDir]/downloaded_history.txt"),
		ProfileFile = new(@"TODO"),
		YTDLPExe = new(@"[$UpperRootDir]/yt-dlp.exe"),
		FFmpegExe = new(@"[$UpperRootDir]/ffmpeg.exe"),
		FirefoxExe = new(@"C:/Program Files/Mozilla Firefox/firefox.exe"),
		YTDLPConfigFileOriginal = new(@"[$ConfigDir]/yt-dlp.conf"),
		YTDLPConfigFile = new("Null"),
		CheckURL = @"https://www.youtube.com/watch?v=dQw4w9WgXcQ",
		CustomYTDLPArguments = "--ppa\" \"EmbedThumbnail+ffmpeg_o:-vf crop=ih:ih",
		SleepInterval = 4,
		MaxSleepInterval = 12, 
		SleepRequests = 3,
		MaxCompressThreads = 8,
		MaxDownloadThreads = 6,
		MaxLyricThreads = 3,
		ScannerSleepIntervalSec = 60,
		ChronDaemonSleepSec = 1800,
		MaxStreamReturnLines = 15000,
		StartingWebServerPort = 50001,
		NormalIntervalSec = 1800,
		CleanIntervalSec = 604800,
		NormalStep1 = true,
		NormalStep2 = true,
		NormalStep3 = true,
		NormalStep4 = true,
		NormalStep5 = true,
		NormalStep6 = true,
		NormalStep7 = true,
		CleanSweepDownload = true,
		CleanSweepLyrics = true,
		CleanSweepCompress = true,
		CleanSweepLore = true,
		Playlists = [
		"https://www.youtube.com/playlist?list=PLqcuYaDDgyacWpBG6ib-2EKOuQa6aGjZJ",
		"https://www.youtube.com/playlist?list=PLqcuYaDDgyaeHKssVjz_Nw3qUDwfrwL09",
		"https://www.youtube.com/playlist?list=PLqcuYaDDgyad_i19iLheoQJLLKJUtwlAr",
		"https://www.youtube.com/playlist?list=PLqcuYaDDgyach02bt_8R8G7AzE9zSAOkS"
		],
		LastCleanRunEpoch = 1785532108,
		LastNormalRunEpoch = 1785673837,
		LogEngine = new(@"[$ConfigDir]/web_console_stream.log")
	};

	// Swap default with null

	public static readonly Profile ErrorProfile = new Profile
	{
		Name = "ERROR",
		BackupDir = new("ERROR"),
		CompressedDirs = [new("ERROR")],
		BrokenSongsFile = new("ERROR"),
		DiagLogFile = new("ERROR"),
		CacheFile = new("ERROR"),
		TimingFile = new("ERROR"),
		CookieFile = new("ERROR"),
		HistoryFile = new("ERROR"),
		ProfileFile = new("ERROR"),
		YTDLPExe = new("ERROR"),
		FFmpegExe = new("ERROR"),
		FirefoxExe = new("ERROR"),
		YTDLPConfigFileOriginal = new("ERROR"),
		YTDLPConfigFile = new("ERROR"),
		CheckURL = "ERROR",
		CustomYTDLPArguments = "ERROR",
		SongFileSearchPattern = "ERROR",
		LyricFileSearchPattern = "ERROR",
		SleepInterval = 2147483647,
		MaxSleepInterval = 2147483647, 
		SleepRequests = 2147483647,
		MaxCompressThreads = 2147483647,
		MaxDownloadThreads = 2147483647,
		MaxLyricThreads = 2147483647,
		ScannerSleepIntervalSec = 2147483647,
		ChronDaemonSleepSec = 2147483647,
		MaxStreamReturnLines = 2147483647,
		StartingWebServerPort = 2147483647,
		NormalIntervalSec = 2147483647,
		CleanIntervalSec = 2147483647,
		NormalStep1 = true,
		NormalStep2 = true,
		NormalStep3 = true,
		NormalStep4 = true,
		NormalStep5 = true,
		NormalStep6 = true,
		NormalStep7 = true,
		CleanSweepDownload = true,
		CleanSweepLyrics = true,
		CleanSweepCompress = true,
		CleanSweepLore = true,
		Playlists = [
		"ERROR",
		"ERROR",
		"ERROR",
		"ERROR"
		],
		LastCleanRunEpoch = 2147483647,
		LastNormalRunEpoch = 2147483647,
		LogEngine = new("ERROR", "ERROR")
	};
}